# Generated by Django 3.2.4 on 2022-03-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('email_id', models.EmailField(blank=True, max_length=50)),
                ('message', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
